sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.4
  
matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: deps=low

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - if [[ "$deps" = "low" ]]; then composer update --prefer-lowest --prefer-stable; else composer install; fi

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/behat
